title: Saturnium

author: stefenmarg

description: 'Saturnium is a barebones jekyll template that everyone can customise easily.'

metadata: 'Saturnium, jekyll, barebones, template, customisable, skeleton'

baseurl: "" 
url: "https://stefenmarg.github.io/"